dist: trusty
sudo: false
language: ruby
rvm:
 - 2.3.0

before_install:
  - nvm use 7.4.0
  - npm install lumo-cljs

test:
  - node_modules/.bin/lumo validate-yaml.clj

script:
  - bundle exec jekyll build
